services:
  database:
    user: "${UID}:${GID}"
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: touchless-kiosk-db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/container/backend
      - ./.env:/container/.env
    env_file:
      - .env
    depends_on:
      - database
